version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=transfer_db
      - POSTGRES_USER=beksultan
      - POSTGRES_PASSWORD=toktobekov
  web:
    build: .
    env_file:
      - .env
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db